# Generated by Django 5.0.1 on 2024-04-02 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fest_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='Contest_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='YEAR', to='Fest_app.year'),
        ),
    ]
